AWSTemplateFormatVersion: '2010-09-09'
Description: 'A.B.R.A. Platform API Gateway for Lambda Functions'

Resources:
  # API Gateway
  ABRAApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: ABRA-Platform-API
      Description: API Gateway for A.B.R.A. Platform Lambda Functions
      EndpointConfiguration:
        Types:
          - REGIONAL

  # Lambda Functions
  RequestPatFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: abra-request-pat
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          const crypto = require('crypto');
          exports.handler = async (event) => {
            const { userId, companyId } = JSON.parse(event.body);
            const patToken = 'PAT-' + crypto.randomBytes(8).toString('hex').toUpperCase();
            const expiry = Date.now() + 900000;
            
            return {
              statusCode: 200,
              headers: {
                'Access-Control-Allow-Origin': '*',
                'Access-Control-Allow-Headers': 'Content-Type',
                'Access-Control-Allow-Methods': 'POST, OPTIONS'
              },
              body: JSON.stringify({
                token: patToken,
                expiry,
                message: 'PAT issued via JIT Access Gate'
              })
            };
          };

  AnchorProofFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: abra-anchor-proof
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          const crypto = require('crypto');
          exports.handler = async (event) => {
            const { hash } = JSON.parse(event.body);
            
            if (!hash || hash.length !== 64) {
              return {
                statusCode: 400,
                headers: { 'Access-Control-Allow-Origin': '*' },
                body: JSON.stringify({ error: 'Invalid hash format' })
              };
            }
            
            return {
              statusCode: 200,
              headers: {
                'Access-Control-Allow-Origin': '*',
                'Access-Control-Allow-Headers': 'Content-Type',
                'Access-Control-Allow-Methods': 'POST, OPTIONS'
              },
              body: JSON.stringify({
                success: true,
                message: 'Backup Proof anchored to DLT',
                hash,
                anchorId: crypto.randomUUID()
              })
            };
          };

  VerifyProofFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: abra-verify-proof
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            const { currentHash } = JSON.parse(event.body);
            
            return {
              statusCode: 200,
              headers: {
                'Access-Control-Allow-Origin': '*',
                'Access-Control-Allow-Headers': 'Content-Type',
                'Access-Control-Allow-Methods': 'POST, OPTIONS'
              },
              body: JSON.stringify({
                isMatch: true,
                status: 'VERIFIED-CLEAN',
                anchoredHash: currentHash
              })
            };
          };

  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/ABRA-DLT-Ledger'

  # API Gateway Resources and Methods
  RequestPatResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ABRAApiGateway
      ParentId: !GetAtt ABRAApiGateway.RootResourceId
      PathPart: request-pat

  RequestPatMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ABRAApiGateway
      ResourceId: !Ref RequestPatResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RequestPatFunction.Arn}/invocations'

  RequestPatOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ABRAApiGateway
      ResourceId: !Ref RequestPatResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  AnchorProofResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ABRAApiGateway
      ParentId: !GetAtt ABRAApiGateway.RootResourceId
      PathPart: anchor-proof

  AnchorProofMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ABRAApiGateway
      ResourceId: !Ref AnchorProofResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AnchorProofFunction.Arn}/invocations'

  VerifyProofResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ABRAApiGateway
      ParentId: !GetAtt ABRAApiGateway.RootResourceId
      PathPart: verify-proof

  VerifyProofMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ABRAApiGateway
      ResourceId: !Ref VerifyProofResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${VerifyProofFunction.Arn}/invocations'

  # Lambda Permissions
  RequestPatPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref RequestPatFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub '${ABRAApiGateway}/*/POST/request-pat'

  AnchorProofPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AnchorProofFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub '${ABRAApiGateway}/*/POST/anchor-proof'

  VerifyProofPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref VerifyProofFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub '${ABRAApiGateway}/*/POST/verify-proof'

  # API Gateway Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - RequestPatMethod
      - AnchorProofMethod
      - VerifyProofMethod
    Properties:
      RestApiId: !Ref ABRAApiGateway
      StageName: prod

Outputs:
  ApiGatewayUrl:
    Description: 'API Gateway URL for A.B.R.A. Platform'
    Value: !Sub 'https://${ABRAApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod'
    Export:
      Name: ABRA-ApiGatewayUrl